#include "catalog.h"
#include "pronto_data.h"

// GENERADO POR scripts/gen_catalog.py — NO EDITAR A MANO.
// Fuente: data/presets/*.json (exportaciones del generador web).
// Regenerar con: make catalog

const Command COMMANDS[] = {
  { "CAP_00",  "Rojo",              "Red",               "P_PULSO_00",              "P_PULSO_00",              0xF02000, P_CAP_00, Mode::CAPTURAS },
  { "CAP_01",  "Naranja",           "Orange",            "P_PULSO_01",              "P_PULSO_01",              0xF05000, P_CAP_01, Mode::CAPTURAS },
  { "CAP_02",  "Naranja oscuro",    "Dark orange",       "P_PULSO_02",              "P_PULSO_02",              0xB84400, P_CAP_02, Mode::CAPTURAS },
  { "CAP_03",  "Amarillo dorado",   "Golden yellow",     "P_PULSO_03",              "P_PULSO_03",              0xE4BC00, P_CAP_03, Mode::CAPTURAS },
  { "CAP_04",  "Ámbar",             "Amber",             "P_PULSO_04",              "P_PULSO_04",              0xE49400, P_CAP_04, Mode::CAPTURAS },
  { "CAP_05",  "Oliva",             "Olive",             "P_PULSO_05",              "P_PULSO_05",              0xB8BC00, P_CAP_05, Mode::CAPTURAS },
  { "CAP_06",  "Verde",             "Green",             "P_PULSO_06",              "P_PULSO_06",              0x10D000, P_CAP_06, Mode::CAPTURAS },
  { "CAP_07",  "Verde claro",       "Light green",       "P_PULSO_07",              "P_PULSO_07",              0x84F05C, P_CAP_07, Mode::CAPTURAS },
  { "CAP_08",  "Verde menta",       "Mint green",        "P_PULSO_08",              "P_PULSO_08",              0x68F0A0, P_CAP_08, Mode::CAPTURAS },
  { "CAP_09",  "Cian",              "Cyan",              "P_PULSO_09",              "P_PULSO_09",              0x34F0FC, P_CAP_09, Mode::CAPTURAS },
  { "CAP_10",  "Azul cielo",        "Sky blue",          "P_PULSO_10",              "P_PULSO_10",              0x1094DC, P_CAP_10, Mode::CAPTURAS },
  { "CAP_11",  "Azul",              "Blue",              "P_PULSO_11",              "P_PULSO_11",              0x480CFC, P_CAP_11, Mode::CAPTURAS },
  { "CAP_12",  "Morado",            "Purple",            "P_PULSO_12",              "P_PULSO_12",              0x8838FC, P_CAP_12, Mode::CAPTURAS },
  { "CAP_13",  "Púrpura",           "Deep purple",       "P_PULSO_13",              "P_PULSO_13",              0xB80CDC, P_CAP_13, Mode::CAPTURAS },
  { "CAP_14",  "Ciruela",           "Plum",              "P_PULSO_14",              "P_PULSO_14",              0x840C5C, P_CAP_14, Mode::CAPTURAS },
  { "CAP_15",  "Frambuesa",         "Raspberry",         "P_PULSO_15",              "P_PULSO_15",              0xE4385C, P_CAP_15, Mode::CAPTURAS },
  { "CAP_16",  "Fucsia",            "Fuchsia",           "P_PULSO_16",              "P_PULSO_16",              0xCC0C5C, P_CAP_16, Mode::CAPTURAS },
  { "CAP_17",  "Rosa",              "Pink",              "P_PULSO_17",              "P_PULSO_17",              0xEC74A0, P_CAP_17, Mode::CAPTURAS },
  { "CAP_18",  "Melocotón",         "Peach",             "P_PULSO_18",              "P_PULSO_18",              0xF09C5C, P_CAP_18, Mode::CAPTURAS },
  { "CAP_19",  "Salmón",            "Salmon",            "P_PULSO_19",              "P_PULSO_19",              0xF0745C, P_CAP_19, Mode::CAPTURAS },
  { "CAP_20",  "Lavanda",           "Lavender",          "P_PULSO_20",              "P_PULSO_20",              0xB894FC, P_CAP_20, Mode::CAPTURAS },
  { "CAP_21",  "Verde lima",        "Lime green",        "P_PULSO_21",              "P_PULSO_21",              0xCCF05C, P_CAP_21, Mode::CAPTURAS },
  { "CAP_22",  "Azul pálido",       "Pale blue",         "P_PULSO_22",              "P_PULSO_22",              0xB8D0FC, P_CAP_22, Mode::CAPTURAS },
  { "CAP_23",  "Violeta",           "Violet",            "P_PULSO_23",              "P_PULSO_23",              0xB80CFC, P_CAP_23, Mode::CAPTURAS },
  { "CAP_24",  "Magenta",           "Magenta",           "P_PULSO_24",              "P_PULSO_24",              0xF034FC, P_CAP_24, Mode::CAPTURAS },

  { "BAS_00",  "Rojo pleno",        "Full red",          "",                        "",                        0xFC0000, P_BAS_00, Mode::BASICOS },
  { "BAS_01",  "Verde pleno",       "Full green",        "",                        "",                        0x00FC00, P_BAS_01, Mode::BASICOS },
  { "BAS_02",  "Azul pleno",        "Full blue",         "",                        "",                        0x0000FC, P_BAS_02, Mode::BASICOS },
  { "BAS_03",  "Cyan",              "Cyan",              "",                        "",                        0x00FCFC, P_BAS_03, Mode::BASICOS },
  { "BAS_04",  "Magenta",           "Magenta",           "",                        "",                        0xFC00FC, P_BAS_04, Mode::BASICOS },
  { "BAS_05",  "Amarillo",          "Yellow",            "",                        "",                        0xFCFC00, P_BAS_05, Mode::BASICOS },
  { "BAS_06",  "Blanco",            "White",             "",                        "",                        0xFCFCFC, P_BAS_06, Mode::BASICOS },
  { "BAS_07",  "Blanco cálido",     "Warm white",        "",                        "",                        0xFCB46C, P_BAS_07, Mode::BASICOS },
  { "BAS_08",  "Blanco frío",       "Cool white",        "",                        "",                        0xD8ECFC, P_BAS_08, Mode::BASICOS },
  { "BAS_09",  "Apagado",           "Off",               "Corta el efecto en curso", "Cuts off the running effect", 0x000000, P_BAS_09, Mode::BASICOS },

  { "ENV_00",  "Destello",          "Flash",             "Ataque instantáneo, 32 ms de sostén", "Instant attack, 32 ms sustain", 0xFCFCFC, P_ENV_00, Mode::ENVOLVENTES },
  { "ENV_01",  "Pulso corto",       "Short pulse",       "32 / 96 / 96 ms",         "32 / 96 / 96 ms",         0xFC5000, P_ENV_01, Mode::ENVOLVENTES },
  { "ENV_02",  "Respiración",       "Breathing",         "960 ms de subida y bajada", "960 ms up and down",      0x008CFC, P_ENV_02, Mode::ENVOLVENTES },
  { "ENV_03",  "Fundido lento",     "Slow fade",         "2.4 s de subida, casi 4.4 s en total", "2.4 s rise, nearly 4.4 s in total", 0xB400FC, P_ENV_03, Mode::ENVOLVENTES },
  { "ENV_04",  "Onda larga",        "Long wave",         "El envolvente más largo posible", "The longest envelope available", 0x00FCB4, P_ENV_04, Mode::ENVOLVENTES },
  { "ENV_05",  "Golpe seco",        "Sharp hit",         "Sustain 0: apenas un parpadeo", "Sustain 0: barely a blink", 0xFC003C, P_ENV_05, Mode::ENVOLVENTES },
  { "ENV_06",  "Brasa",             "Ember",             "Sube en 480 ms y se apaga muy despacio", "Rises in 480 ms, fades very slowly", 0xFC6400, P_ENV_06, Mode::ENVOLVENTES },
  { "ENV_07",  "Latido",            "Heartbeat",         "Corto y con cola",        "Short, with a tail",      0xFC0000, P_ENV_07, Mode::ENVOLVENTES },

  { "MUL_00",  "Chispeo denso",     "Dense sparkle",     "67 % de los dispositivos", "67 % of devices",         0xFCFCFC, P_MUL_00, Mode::MULTITUD },
  { "MUL_01",  "Chispeo medio",     "Medium sparkle",    "50 %",                    "50 %",                    0xFCECB4, P_MUL_01, Mode::MULTITUD },
  { "MUL_02",  "Chispeo disperso",  "Sparse sparkle",    "16 %",                    "16 %",                    0xB4DCFC, P_MUL_02, Mode::MULTITUD },
  { "MUL_03",  "Estrellas raras",   "Rare stars",        "4 %, puntos aislados en la multitud", "4 %, isolated dots in the crowd", 0xFCFCD8, P_MUL_03, Mode::MULTITUD },
  { "MUL_04",  "Lluvia azul",       "Blue rain",         "32 %, envolvente suave",  "32 %, soft envelope",     0x0078FC, P_MUL_04, Mode::MULTITUD },
  { "MUL_05",  "Ascuas dispersas",  "Scattered embers",  "10 %, muy lento",         "10 %, very slow",         0xFC3C00, P_MUL_05, Mode::MULTITUD },

  { "ESC_00",  "Atardecer · 1",     "Sunset · 1",        "",                        "",                        0xFC7800, P_ESC_00, Mode::ESCENAS },
  { "ESC_01",  "Atardecer · 2",     "Sunset · 2",        "",                        "",                        0xFC3C28, P_ESC_01, Mode::ESCENAS },
  { "ESC_02",  "Atardecer · 3",     "Sunset · 3",        "",                        "",                        0xB41450, P_ESC_02, Mode::ESCENAS },
  { "ESC_03",  "Océano · 1",        "Ocean · 1",         "",                        "",                        0x0064B4, P_ESC_03, Mode::ESCENAS },
  { "ESC_04",  "Océano · 2",        "Ocean · 2",         "",                        "",                        0x00B4C8, P_ESC_04, Mode::ESCENAS },
  { "ESC_05",  "Océano · 3",        "Ocean · 3",         "",                        "",                        0x003C8C, P_ESC_05, Mode::ESCENAS },
  { "ESC_06",  "Bosque · 1",        "Forest · 1",        "",                        "",                        0x14A028, P_ESC_06, Mode::ESCENAS },
  { "ESC_07",  "Bosque · 2",        "Forest · 2",        "",                        "",                        0x78C800, P_ESC_07, Mode::ESCENAS },
  { "ESC_08",  "Neón · 1",          "Neon · 1",          "",                        "",                        0xFC00C8, P_ESC_08, Mode::ESCENAS },
  { "ESC_09",  "Neón · 2",          "Neon · 2",          "",                        "",                        0x00FCDC, P_ESC_09, Mode::ESCENAS },
  { "ESC_10",  "Neón · 3",          "Neon · 3",          "",                        "",                        0xC8FC00, P_ESC_10, Mode::ESCENAS },
  { "ESC_11",  "Hielo · 1",         "Ice · 1",           "",                        "",                        0xC8F0FC, P_ESC_11, Mode::ESCENAS },
  { "ESC_12",  "Hielo · 2",         "Ice · 2",           "",                        "",                        0x78C8FC, P_ESC_12, Mode::ESCENAS },

  { "GRP_00",  "Broadcast",         "Broadcast",         "Grupo 0: todos",          "Group 0: everyone",       0xFCFCFC, P_GRP_00, Mode::GRUPOS },
  { "GRP_01",  "Grupo 1 · rojo",    "Group 1 · red",     "",                        "",                        0xFC0000, P_GRP_01, Mode::GRUPOS },
  { "GRP_02",  "Grupo 2 · verde",   "Group 2 · green",   "",                        "",                        0x00FC00, P_GRP_02, Mode::GRUPOS },
  { "GRP_03",  "Grupo 3 · azul",    "Group 3 · blue",    "",                        "",                        0x0000FC, P_GRP_03, Mode::GRUPOS },
  { "GRP_04",  "Grupo 4 · ámbar",   "Group 4 · amber",   "",                        "",                        0xFCA000, P_GRP_04, Mode::GRUPOS },
};

const uint16_t COMMAND_COUNT = sizeof(COMMANDS) / sizeof(COMMANDS[0]);

const CategoryInfo CATEGORIES[MODE_COUNT] = {
  { "CAPTURAS",     "Capturas",     "Captures",    
    "Colores decodificados de capturas reales. La referencia de compatibilidad más fiable.",
    "Colors decoded from real captures. The most reliable compatibility reference." },
  { "BASICOS",      "Básicos",      "Basics",      
    "Primarios y secundarios al máximo que el badge puede representar.",
    "Primaries and secondaries at the maximum the badge can represent." },
  { "ENVOLVENTES",  "Envolventes",  "Envelopes",   
    "Un mismo color con distinta forma temporal: attack, sustain y release.",
    "One color with different shapes over time: attack, sustain and release." },
  { "MULTITUD",     "Multitud",     "Crowd",       
    "Usan el campo chance: solo una fracción aleatoria de los badges responde.",
    "They use the chance field: only a random fraction of badges responds." },
  { "ESCENAS",      "Escenas",      "Scenes",      
    "Paletas coherentes pensadas para lanzarse en secuencia.",
    "Coherent palettes meant to be fired in sequence." },
  { "GRUPOS",       "Grupos",       "Groups",      
    "El mismo color restringido a un group id. Solo responden los badges de ese grupo.",
    "The same color restricted to a group id. Only badges in that group respond." },
};
